Npm install bcrypt-nodejs --save
Npm install body-parser --save
Npm install connect-multiparty --save
Npm install core-util-is --save
Npm install express --save
Npm install fs --save
Npm install jwt-decode --save
Npm install jwt-simple --save
Npm install moment --save
Npm install mongo --save
Npm install mongodb --save
Npm install mongoose --save
Npm install mongoose-pagination --save
Npm install nodemon --save
Npm install operations --save
Npm install path --save
